// flow-typed signature: 3b62613c7408b5a41bb444251a5be95f
// flow-typed version: <<STUB>>/localforage_v1.5.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'localforage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'localforage' {
    declare interface Localforage {
        getItem (name: string): Promise<any>;
        setItem (name: string, value: any): void;
    }
    declare var exports: Localforage;
}
