// flow-typed signature: 3b57818171f35b3204be29a8238d448b
// flow-typed version: <<STUB>>/vue_vlatest/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue' {
  declare module.exports: any;
}
